apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opal
resources:
  - service-monitor.yaml
  - alerts.yaml
configMapGenerator:
  - name: prismfs-grafana-dashboard
    files:
      - prismfs.json
    options:
      labels:
        grafana_dashboard: "1"
generatorOptions:
  disableNameSuffixHash: true
