apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prismfs
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prismfs
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
  targetLabels:
    - app.kubernetes.io/instance
