version: 2
updates:
  - package-ecosystem: cargo
    directory: /services/prismfs
    schedule:
      interval: weekly
  - package-ecosystem: composer
    directory: /apps/web
    schedule:
      interval: weekly
  - package-ecosystem: bun
    directory: /apps/web
    schedule:
      interval: weekly
