<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(RevitTargetFramework)</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>Opal.Revit</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Opal.Client/Opal.Client.csproj" />
    <PackageReference Include="Nice3point.Revit.Api.RevitAPI" Version="$(RevitApiVersion)" PrivateAssets="all" />
    <PackageReference Include="Nice3point.Revit.Api.RevitAPIUI" Version="$(RevitApiVersion)" PrivateAssets="all" />
  </ItemGroup>
</Project>
