<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TestTargetFramework Condition="'$(TestTargetFramework)' == ''">net10.0</TestTargetFramework>
    <TargetFramework>$(TestTargetFramework)</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Opal.Client/Opal.Client.csproj" />
  </ItemGroup>
</Project>
