<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(RevitTargetFramework)</TargetFramework>
    <AssemblyName>Opal.Revit.Bootstrap</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Nice3point.Revit.Api.RevitAPI" Version="$(RevitApiVersion)" PrivateAssets="all" />
    <PackageReference Include="Nice3point.Revit.Api.RevitAPIUI" Version="$(RevitApiVersion)" PrivateAssets="all" />
  </ItemGroup>
</Project>
