[package]
name = "prismfs-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
prismfs-cache.workspace = true
prismfs-core.workspace = true
prismfs-fuse.workspace = true
prismfs-policy.workspace = true
prismfs-storage.workspace = true
prismfs-telemetry.workspace = true
tokio.workspace = true
tracing.workspace = true

[lints]
workspace = true
