[package]
name = "prismfs-fuse"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
fuser.workspace = true
prismfs-cache.workspace = true
prismfs-core.workspace = true
prismfs-policy.workspace = true
prismfs-storage.workspace = true
thiserror.workspace = true

[lints]
workspace = true
