[package]
name = "prismfs-cache"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
async-trait.workspace = true
bytes.workspace = true
dashmap.workspace = true
prismfs-core.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
